site_name: PHYSTAT 
repo_name: GitHub
repo_url: https://github.com/PhyStat/Website
edit_uri: edit/main/docs

nav:
  - Home: index.md
  - Phystat Seminars: seminars.md
  - Phystat Workshops and Schools: workshops.md

theme: cosmo
#theme: united

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

markdown_extensions:
    - pymdownx.arithmatex
    - pymdownx.details
    - pymdownx.blocks.details
    - admonition
